# mamba env create --file=
name: classification
channels:
  - conda-forge
dependencies:
  - asf_search=10.1.0
  - cartopy=0.25.0
  - contextily=1.6.2
  - earthengine-api=1.6.9
  - gdal=3.10.3
  - geemap=0.36.4
  - geopandas=1.1.1
  - imbalanced-learn=0.12.2
  - ipykernel=6.30.1
  - ipympl=0.9.7
  - jupyter=1.1.1
  - matplotlib=3.10.6
  - matplotlib-scalebar=0.9.0
  - owslib=0.34.1
  - pyogrio=0.11.0
  - py6s=1.9.2
  - pypdf=6.1.1
  - python=3.12.11
  - rasterstats=0.20.0
  - scikit-learn=1.4.2
  - seaborn=0.13.2
  - shap=0.48.0
  - shapely=2.1.2
  - pip=25.2
  # Moran's I packages
  - pysal=25.7
  - esda=2.8.0
  # NFI management
  - pip:
      - dbfread==2.0.7
      - pyodbc==5.2.0
      - tabulate==0.9.0